#!/usr/bin/env python
import yad,os
defaults = {
'icon': 'gnome-panel-launcher.png',
'home' : os.path.expanduser("~"),
'user' : os.getenv("USER"),
'sudo-user' : os.getenv("SUDO_USER")
}

if defaults["sudo-user"] == None:
    print("Error:Please run the program as root!")
    exit(1)

yad = yad.YAD()
data = (
("CB","Type",("^Application","Application in terminal","location")),
("","Name",""),
("","Command",""),
("FL","Icon",defaults['icon']),
("","Comment","")
)
while True:
    form = yad.Form(fields=data,title="Gnome Desktop Entry Editor",window_icon=defaults['icon'],center=True,width=480)
    if form:
        errors = []
        for i in [1,2,4]:
            if len(form[i].strip()) == 0:
                errors.append(data[i][1])
        if errors:
            error,rc = yad.execute(title="Gnome Desktop Entry Editor",
            text="<b> Please fill out the "+", ".join(errors)+" fields. </b>",text_align="center",
            image="gtk-dialog-error",window_icon=defaults['icon'],center=True,
            dialog_sep=True,button1="gtk-ok:0")
            if rc == 0:
                continue
            else:
                exit(1)
        break
    else:
        exit(1)
